[project]
name = "llm-asset-sentiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "deepmultilingualpunctuation>=1.0.1",
    "ipykernel>=6.29.5",
    "pytube>=15.0.0",
    "requests>=2.32.3",
    "transformers>=4.49.0",
    "youtube-transcript-api>=0.6.3",
]
